apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: clickhouse
    jsonData:
      defaultDatabase: pipeline
      host: clickhouse
      port: 9000
      protocol: native
      username: web_user
      secure: false
    secureJsonData:
      password: password
    editable: true
